navbar2:
  - {item: Create, href: "#about", class: active, icon: "edit"}
  - {item: Customize, href: "#contact", icon: "hand-right"}
  - {item: Frameworks, href: "#frameworks", dropdown: true, class: dropdown, 
     menu: [{item: io2012}, {item: shower}]
    }
  - {item: Lessons, href: "#lessons", dropdown: true, class: dropdown, 
     menu: [{item: Lesson1, href: "lesson1.html"}, {item: Lesson2}]
    }
title: Slidify
favicon: slidify_logo
navbar:
    - {item: Home, href: 'index.html', icon: home}
    - {item: "Start", href: 'start.html', class: active, icon: signin}
    - {item: Create, href: 'create.html', icon: pencil}
    - {item: Customize, href: style, icon: gift, class: dropdown, 
        dropdown: true, menu: [
         {item: Frameworks, href: 'frameworks.html', icon: ""},
         {item: Widgets, href: 'widgets.html', icon: ""},
         {item: Layouts, href: 'layouts.html', icon: ""},
        ]
      }
    - {item: Share, href: "share.html", icon: gift}
github: {user: ramnath, repo: slidify}
