navbar2:
  - {item: Create, href: "#about", class: active, icon: "edit"}
  - {item: Customize, href: "#contact", icon: "hand-right"}
  - {item: Frameworks, href: "#frameworks", dropdown: true, class: dropdown, 
     menu: [{item: io2012}, {item: shower}]
    }
  - {item: Lessons, href: "#lessons", dropdown: true, class: dropdown, 
     menu: [{item: Lesson1, href: "lesson1.html"}, {item: Lesson2}]
    }
title: Slidify
favicon: slidify_logo
navbar:
    - {item: Home, href: 'index.html', icon: home}
    - {item: "Start", href: 'start.html', class: active, icon: signin}
    - {item: Author, href: about, icon: pencil}
    - {item: Style, href: style, icon: hand-right, class: dropdown, 
        dropdown: true, menu: [
         {item: io2012, href: 'samples/intro'},
         {item: deck.js, href: 'samples/deck.js'},
         {item: shower, href: 'samples/shower'},
         {item: landslide, href: 'samples/landslide'}
        ]
      }
    - {item: Customize, href: customize, icon: gift}
    - {item: Extend, href: extend, icon: cogs}
    - {item: Publish, href: publish,  icon: github}
